### PR TITLE
Fix fatal error being thrown when no related contacts are found for token

### PR DESCRIPTION
**Pull request by dejan9393**

### CODE REVIEW

**Comment by andrewperry** [comment]
Just giving this a bump so that we don't see regressions in future....

**Comment by MegaphoneJon** [comment]
@dejan9393 I think this is also fixed by #8 which is merged, please test and see if this can be closed?

**Comment by MegaphoneJon** [comment]
Err, I think #6 is the equivalent fix.  Either way, the current master branch shouldn't have this bug.

**Comment by MegaphoneJon** [comment]
Recommend closing this since it should be fixed for a while now (see above)

**Comment by twomice** [comment]
Right, thanks @MegaphoneJon .

Closing. If you feel this needs further attention, please re-open and provide additional details.

**Pull request closed without merging**
